spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/startSnow/config-repo
          basedir: /home/chixue/repo
          delete-untracked-branches: false

       
        
