spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          repos:
            open-cloud:
              pattern:
                - '*/development'
                - '*/staging'
              uri: https://github.com/startSnow/open-cloud
              
              
