eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 1234
spring:
  application:
    name: client-ribbon-properties-customiz
CLIENT:
  ribbon:
    listOfServers: 127.0.0.1:1211