eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/startSnow/config-simple
##127.0.0.1:8080/local-default.yml 访问路径